# Example command:
#   Humble on a NVIDIA system:
#   DOCKER_IMAGE=humble-humble-tutorial-source docker compose run gpu
#   Rolling without discrete graphics:
#   DOCKER_IMAGE=main-rolling-tutorial-source compose run cpu
#
# Optional overrides:
#   VLAPB_ROOT=/path/to/VLAPB
#   XAUTHORITY=/tmp/.docker.xauth

services:
  cpu:
    image: moveit/moveit2:${DOCKER_IMAGE:-main-rolling-tutorial-source}
    privileged: true
    network_mode: host
    working_dir: /home/artemis/Documents/VLAPB/libero/teleop_moveit
    command: /bin/bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-/tmp/.Xauthority}:/root/.Xauthority:ro
      - ${VLAPB_ROOT:-/home/artemis/Documents/VLAPB}:/home/artemis/Documents/VLAPB
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
      VLAPB_ROOT: /home/artemis/Documents/VLAPB
  gpu:
    image: moveit/moveit2:${DOCKER_IMAGE:-main-rolling-tutorial-source}
    privileged: true
    network_mode: host
    working_dir: /home/artemis/Documents/VLAPB/libero/teleop_moveit
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-/tmp/.Xauthority}:/root/.Xauthority:ro
      - ${VLAPB_ROOT:-/home/artemis/Documents/VLAPB}:/home/artemis/Documents/VLAPB
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
      VLAPB_ROOT: /home/artemis/Documents/VLAPB
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
